sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t kabeerchoudary/node_nginx -f Dockerfile.dev .

script:
    - docker run -e CI=true kabeerchoudary/node_nginx npm run test -- --coverage