version: '3'
services:
    react-app:
        #image: bc999c27889f
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "4000:3000"
        volumes:
            - /app/node_modules
            - H:\Docker_practices\react_container\frontend:/app